config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :invitation , only: :edit
  resources :chats
 Plezi.route '/ws', WebsocketController

  root to: "static_pages#index"

  get "/invitation/:id/:idr" => "invitation#insert"

  get "/chats/:id/:idr" => "chats#show_messages" 

  post "/chats/:id/:idr/:text" => "chats#create" 

  

  get "/users/chats" => "chats#chat"

 devise_scope :user do 

    get '/users' , to: "static_pages#home"

    delete  '/users/sign_out' => 'static_pages#destroy'

 end

end

app/models/chat.rb
class Chat < ActiveRecord::Base

	belongs_to :sender , class_name: "Users"
	belongs_to :receiver , class_name: "Users"
	

	def self.show_chat (user1 , user2)

	Chat.find_by_sql ["select text,created_at from chats where sender_id= ? and receiver_id= ? OR sender_id= ? and receiver_id= ? 
						ORDER BY created_at" , user1,user2,user2,user1]
		
	end


end

app/models/friendship.rb
class Friendship < ActiveRecord::Base

	belongs_to :sender , class_name: "User"
	belongs_to :receiver , class_name: "User"


	def self.select_friends (user1)

		Friendship.find_by_sql ["select * from friendships where sender_id= ? or receiver_id= ? " , user1,user1 ]
		
	end


end

app/models/invitation.rb
class Invitation < ActiveRecord::Base


	belongs_to :sender , class_name: "User"
	belongs_to :receiver , class_name: "User"


	def new_token

		SecureRandom.urlsafe_base64
		
	end


	

end

app/models/user.rb
class User < ActiveRecord::Base


	has_many :invitations 

	has_many :sent_messages , class_name: "Chat" , foreign_key: "sender_id" , dependent: :destroy
	has_many :received_messages , class_name: "Chat" , foreign_key: "receiver_id" , dependent: :destroy

	# Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


         def self.select_users(user1)

         	User.find_by_sql ["select * from users where id  not IN  (select sender_id from friendships where receiver_id = ? UNION 
                              select receiver_id from friendships where sender_id = ? )", user1 , user1]
         	
         end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   before_action :configure_permitted_parameters, if: :devise_controller?


   # This after function is used for redirecting of a page after successfull sign in .
   # It redirects it to the users show page if successfully signed in.

    def after_sign_in_path_for(resource)
   		
   		users_path
	end

   protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController



	def index
		
	end


	def show_messages

		# here we have used 2 ways of displaying all the texts of 2 persons chatting . 
		# First is by taking the results of sender and receiver separetly in different variables and 
		# then concatenating both in the result variable by sorting it according to the created_at time.

		# @ms = current_user.sent_messages.where(receiver_id: params[:idr]).order('created_at DESC')
		# @mr = current_user.received_messages.where(sender_id: params[:idr]).order('created_at DESC')
		# @result = (@ms + @mr).sort_by{ |c| c.created_at }

		# # Second is , by directly applying the Raw Sql query in the model and retrieving the the result in 
		# an instance variable and then just loop through that variable to display the messages.
		# Here we will use the 2nd method as it's more economical to directly apply the raw sql query
		# rather then creating 3 instance variable and then sorting them , this approach takes more 
		# time in larger databases while retreiving the records.

		@result = Chat.show_chat(current_user.id , params[:idr])

 		@m = Chat.new

		respond_to do |format|
		    
		    format.html 
		    format.js
		  end

	end


	def create

		if params[:chat][:sender_id].to_i != current_user.id  		# The below code is for the scenario when the user2 has invited user1 and in the frienship
																	# database the entry is like 10 , 9 . Now when 9 sends the message the link on send message take the 
																	# sender and receiver ids from frienships table where in out case the entry is 10 ,9 . And therefore
																	# the entry in the chat table will be created wrong as 10 , 9 while it should be 9,10. So , here we 
																	# have checked whether the sender id in params hash is the current user or not . If not , we have 
																	# changed it by assigning the correct interchanged value of id in idr.	

				params[:chat][:receiver_id] = params[:chat][:sender_id]

		end


		@msg=Chat.new

		@msg.sender_id = current_user.id
		@msg.receiver_id = params[:chat][:receiver_id]
		@msg.text = params[:chat][:text]

		if @msg.save

			puts "chat entry created succesfulllyy"
			# broadcast the update.
			WebsocketController.broadcast :message_waiting,
			          from: @msg.sender_id,
			          to: @msg.receiver_id,
			          text: @msg.text,
			          msg: :chat
		end
		@m = Chat.new
		@result = Chat.show_chat(current_user.id , params[:chat][:receiver_id])
		respond_to do |format|
		    
		    format.html	# here you can also use redirect_to request.referrer }
		    format.js
		 end
		
		
	end

	def chat

			@fr=Friendship.select_friends(current_user)


			
	end



end

app/controllers/invitation_controller.rb
class InvitationController < ApplicationController


	def insert

		
		if Friendship.exists?(:sender_id => params[:id] , :receiver_id => params[:idr])


				puts "You are already friend with this user ......"

				flash[:notice] = "YYou are already friend with this user"


		elsif Friendship.exists?(:sender_id => params[:idr] , :receiver_id => params[:id])


				puts "Youuu are alsooo connncected with your friend ..... !!!!!!!!!!!!!!"
					
				flash[:notice] = "YYou are already friend with this user"

		else

				@user=Invitation.new

				@user.sender_id = params[:id]

				@user.receiver_id = params[:idr]

				@user.token = SecureRandom.urlsafe_base64

				if @user.sender_id == @user.receiver_id 

					puts "You can't add yourself"

					 flash[:notice] = "You can't add yourself"

				else

						if  @user.save

						#	@user = User.find(@user.receiver) # We have altered the user variable by getting the id of receiver's 
															  # from the User table so that we can retrieve it's email in the mailer's view directly.

							UserMailer.account_invitation(@user).deliver_now

							puts "mail sent successfully........"

							flash[:success] = "mail sent successfully	"
											 	
						end

				end

			
		end


		redirect_to users_path
		
	end



	def edit

	#	inv = Invitation.find_by(receiver: params[:receiver]).where(token: params[:id])

		inv = Invitation.find_by(token: params[:id])

	
		if inv

			puts "the token matched in the database ...... "
	
		end


		fr = Friendship.new

		fr.sender_id = inv.sender_id
		fr.receiver_id = inv.receiver_id

		if fr.save

			puts "values added in the friendship table......"
			
		end

		

		redirect_to users_path
		
	end



end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	before_action :user_signed_in?


	def index
		
	end


	def home

		@users=User.select_users(current_user)  # This query in database will select only those users
								   # who are not yet a friend of the current user . 
								   # Friends with the current user won't be displayed here 
								   # according to this query.

	end

	

	

	def destroy

		User.find(params[:id]).destroy
		
		redirect_to @users
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/invitation_helper.rb
module InvitationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/chats/_message_display.html.erb
<% @result.each do |m| %>
	
	<%= m.text %> &emsp; <br />
 
<% end %>
<%= form_for(@m , url: chats_path , remote: true ) do |f| %>

		      <%= f.label :Text %>
		      <%= f.text_field :text, class: 'form-control' %>

		   <%= f.hidden_field :sender_id, value: params[:id] %>
		    <%= f.hidden_field :receiver_id, value: params[:idr] %>


		      <%= f.submit "Save Changes", class: "btn btn-primary" %>
		  <% end %>

app/views/chats/chat.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Linked Chats</title>
<%= stylesheet_link_tag 'style', media: 'all',
                                           'data-turbolinks-track' => true %>

</head>
<body>


	<!-- ---------------	Displays the list of Friends  --------------------- -->


		<div class="left-pane">

				<div class="left-pane-header-text" >
					
					<h2> Friends</h2>

				</div>

					
					<ul class="left-pane-list">
						
						<% @fr.each do |f| %>

						
						<% if f.sender_id == current_user.id %>

								<%= f.receiver.email %>
															<!-- here the below receiver_id is used to fetch the receiver id from the friendship table and we use it in the send message link -->
							<% receiver_id = f.receiver.id %>          

						<% elsif f.receiver_id == current_user.id %>
						

								<%= f.sender.email %>
									<% receiver_id = f.sender.id %>

						<%end%>
							
							 
							<%= link_to "Send Message" , {:controller => "chats", :action => "show_messages", :id => current_user.id , :idr =>  receiver_id , remote: true} %> <br />

						<%end%>

					</ul>
			
		</div>

		<!-- ---------------	End of Left Panel. --------------------- -->
		
		<div class="chat-content">

			<div class="chat-content-header">

				<h1> Chat Box </h1>

			</div>


			<div class="chatcontainer">

				<div class="chatheader">

					<h3>Welcome <%= current_user.email %>.</h3>					

				</div>

				<div class="chatmessages" >

						<div id="task-form" display:none >
						<% if !@result.nil? %>	
						<%= render 'message_display' %>
						<% end %>
						</div>
					
				</div>
				
		
		
		
			</div>

		</div>


</body>
</html>

app/views/chats/create.js.erb
$("#task-form").html("<%= escape_javascript(render('message_display')) %>");

app/views/chats/show_messages.js.erb
$("#task-form").html("<%= escape_javascript(render('message_display')) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Linkedchats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="header">

				<div class="header-text">
					
					<h1> Linked Chats</h1>

				</div>		
				
					  <div class="wrap">

					 	 <% if current_user.present? %>

					 	 		<%= link_to "Home" , users_path , class: 'button'%>&nbsp;&nbsp;

					 		 <%= link_to "Friends" , users_chats_path , class: 'button'%>&nbsp;&nbsp;

					 		 <%= link_to "Log Out" , destroy_user_session_path ,class: 'button', method: :DELETE %>&nbsp;

					 	 <% else %>
					  
						 <%= link_to "Sign In" , new_user_session_path , class: 'button'%>

					 	 <% end %>


					  </div>

				
			
		</div>

		<div class="clearfix"></div>

	<!-- ---------------	End of Header --------------------- -->

 <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
 <% end %>

 

<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<ul class="users">

<h1> Professionals that are currently registered with linkedchats.</h1>

<!--  This below minus will the remove the current user from the list of 
      of users being displayed . All users except the current user will be 
      displayed here . -->

	<% (@users - [ current_user ]).each do |us| %>      
  	

	<li> <%= us.email %> 
	<%= link_to "Add" , {:controller => "invitation", :action => "insert", :idr => us.id , :id => current_user.id } %></li> 


	<br />

  <% end %>

	

  
</ul>

app/views/static_pages/index.html.erb
Sign In here if you are a registered user. 

<%= link_to "Sign In" , new_user_session_path %> <br />

Register your new account here .

<%= link_to "Sign Up" , new_user_registration_path %>